package com.example.demo.dao;

import com.example.demo.DataObject.UserPasswordDo;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    long countByExample(UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int deleteByExample(UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int insert(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int insertSelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    List<UserPasswordDo> selectByExample(UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    UserPasswordDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") UserPasswordDo record, @Param("example") UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int updateByExample(@Param("record") UserPasswordDo record, @Param("example") UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 17 23:32:31 GMT+08:00 2021
     */
    int updateByPrimaryKey(UserPasswordDo record);
}