spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: miaosha
    type: com.alibaba.druid.pool.DruidDataSource

#
mybatis:
  mapper-locations: classpath:mapping/*.xml


server:
  port: 8080

