package com.example.demo.dao;

import com.example.demo.DataObject.ItemStockDo;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jul 29 22:38:52 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jul 29 22:38:52 GMT+08:00 2021
     */
    int insert(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jul 29 22:38:52 GMT+08:00 2021
     */
    int insertSelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jul 29 22:38:52 GMT+08:00 2021
     */
    ItemStockDo selectByPrimaryKey(Integer id);

    ItemStockDo selectByItemId(Integer itemId);

    int decreaseStock(@Param("itemId")Integer itemId, @Param("amount") Integer amount);
//    使用@Param注解来声明参数时使用 #{} 或 ${} 的方式都可以 不使用@Param注解时必须使用#{}方式

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jul 29 22:38:52 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jul 29 22:38:52 GMT+08:00 2021
     */
    int updateByPrimaryKey(ItemStockDo record);
}